name: integ-security-k8s-tests
on: [push, pull_request]
jobs:
  run-integ-security:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: prow/integ-suite-kind.sh test.integration.security.kube
